### ISSUE TITLE
Please add an open source license file so code can be reused

### ISSUE THREAD

**Issue by Hedda** [MeisterBob/zigpy_nrf52#1]
@MeisterBob Please consider adding an open-source license file to this repository so the code can be reused by others.

Suggest just copy the license file from zigpy or zigpy-znp but perhaps name it "LICENSE.md" as standard on GitHub now:

https://github.com/zigpy/zigpy-znp/blob/dev/LICENSE

https://github.com/zigpy/zigpy/blob/dev/LICENSE

PS: Related to https://github.com/zigpy/zigpy/issues/394

**Comment by MeisterBob** [comment]
added GPL-3 license
